/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as SignInCallbackRouteImport } from './routes/sign-in/callback'
import { Route as AuthenticatedValidationRouteImport } from './routes/_authenticated.validation'
import { Route as AuthenticatedTradeRouteImport } from './routes/_authenticated.trade'
import { Route as AuthenticatedStrategiesRouteImport } from './routes/_authenticated.strategies'
import { Route as AuthenticatedRunsRouteImport } from './routes/_authenticated.runs'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated.insights'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated.docs'
import { Route as AuthenticatedDataRouteImport } from './routes/_authenticated.data'
import { Route as AuthenticatedValidationStudyIdRouteImport } from './routes/_authenticated.validation_.$studyId'
import { Route as AuthenticatedRunsRunIdRouteImport } from './routes/_authenticated.runs_.$runId'
import { Route as AuthenticatedValidationCampaignsCampaignIdRouteImport } from './routes/_authenticated.validation_.campaigns.$campaignId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInCallbackRoute = SignInCallbackRouteImport.update({
  id: '/sign-in/callback',
  path: '/sign-in/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedValidationRoute = AuthenticatedValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradeRoute = AuthenticatedTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStrategiesRoute = AuthenticatedStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRunsRoute = AuthenticatedRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDataRoute = AuthenticatedDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedValidationStudyIdRoute =
  AuthenticatedValidationStudyIdRouteImport.update({
    id: '/validation_/$studyId',
    path: '/validation/$studyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRunsRunIdRoute = AuthenticatedRunsRunIdRouteImport.update({
  id: '/runs_/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedValidationCampaignsCampaignIdRoute =
  AuthenticatedValidationCampaignsCampaignIdRouteImport.update({
    id: '/validation_/campaigns/$campaignId',
    path: '/validation/campaigns/$campaignId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof AuthenticatedDataRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/runs': typeof AuthenticatedRunsRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/trade': typeof AuthenticatedTradeRoute
  '/validation': typeof AuthenticatedValidationRoute
  '/sign-in/callback': typeof SignInCallbackRoute
  '/sign-in/': typeof SignInIndexRoute
  '/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/validation/$studyId': typeof AuthenticatedValidationStudyIdRoute
  '/validation/campaigns/$campaignId': typeof AuthenticatedValidationCampaignsCampaignIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof AuthenticatedDataRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/runs': typeof AuthenticatedRunsRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/trade': typeof AuthenticatedTradeRoute
  '/validation': typeof AuthenticatedValidationRoute
  '/sign-in/callback': typeof SignInCallbackRoute
  '/sign-in': typeof SignInIndexRoute
  '/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/validation/$studyId': typeof AuthenticatedValidationStudyIdRoute
  '/validation/campaigns/$campaignId': typeof AuthenticatedValidationCampaignsCampaignIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/data': typeof AuthenticatedDataRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/runs': typeof AuthenticatedRunsRoute
  '/_authenticated/strategies': typeof AuthenticatedStrategiesRoute
  '/_authenticated/trade': typeof AuthenticatedTradeRoute
  '/_authenticated/validation': typeof AuthenticatedValidationRoute
  '/sign-in/callback': typeof SignInCallbackRoute
  '/sign-in/': typeof SignInIndexRoute
  '/_authenticated/runs_/$runId': typeof AuthenticatedRunsRunIdRoute
  '/_authenticated/validation_/$studyId': typeof AuthenticatedValidationStudyIdRoute
  '/_authenticated/validation_/campaigns/$campaignId': typeof AuthenticatedValidationCampaignsCampaignIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data'
    | '/docs'
    | '/insights'
    | '/runs'
    | '/strategies'
    | '/trade'
    | '/validation'
    | '/sign-in/callback'
    | '/sign-in/'
    | '/runs/$runId'
    | '/validation/$studyId'
    | '/validation/campaigns/$campaignId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data'
    | '/docs'
    | '/insights'
    | '/runs'
    | '/strategies'
    | '/trade'
    | '/validation'
    | '/sign-in/callback'
    | '/sign-in'
    | '/runs/$runId'
    | '/validation/$studyId'
    | '/validation/campaigns/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/data'
    | '/_authenticated/docs'
    | '/_authenticated/insights'
    | '/_authenticated/runs'
    | '/_authenticated/strategies'
    | '/_authenticated/trade'
    | '/_authenticated/validation'
    | '/sign-in/callback'
    | '/sign-in/'
    | '/_authenticated/runs_/$runId'
    | '/_authenticated/validation_/$studyId'
    | '/_authenticated/validation_/campaigns/$campaignId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInCallbackRoute: typeof SignInCallbackRoute
  SignInIndexRoute: typeof SignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/callback': {
      id: '/sign-in/callback'
      path: '/sign-in/callback'
      fullPath: '/sign-in/callback'
      preLoaderRoute: typeof SignInCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/validation': {
      id: '/_authenticated/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof AuthenticatedValidationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trade': {
      id: '/_authenticated/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof AuthenticatedTradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/strategies': {
      id: '/_authenticated/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof AuthenticatedStrategiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/runs': {
      id: '/_authenticated/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AuthenticatedRunsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data': {
      id: '/_authenticated/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AuthenticatedDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/validation_/$studyId': {
      id: '/_authenticated/validation_/$studyId'
      path: '/validation/$studyId'
      fullPath: '/validation/$studyId'
      preLoaderRoute: typeof AuthenticatedValidationStudyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/runs_/$runId': {
      id: '/_authenticated/runs_/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AuthenticatedRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/validation_/campaigns/$campaignId': {
      id: '/_authenticated/validation_/campaigns/$campaignId'
      path: '/validation/campaigns/$campaignId'
      fullPath: '/validation/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedValidationCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDataRoute: typeof AuthenticatedDataRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedRunsRoute: typeof AuthenticatedRunsRoute
  AuthenticatedStrategiesRoute: typeof AuthenticatedStrategiesRoute
  AuthenticatedTradeRoute: typeof AuthenticatedTradeRoute
  AuthenticatedValidationRoute: typeof AuthenticatedValidationRoute
  AuthenticatedRunsRunIdRoute: typeof AuthenticatedRunsRunIdRoute
  AuthenticatedValidationStudyIdRoute: typeof AuthenticatedValidationStudyIdRoute
  AuthenticatedValidationCampaignsCampaignIdRoute: typeof AuthenticatedValidationCampaignsCampaignIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDataRoute: AuthenticatedDataRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedRunsRoute: AuthenticatedRunsRoute,
  AuthenticatedStrategiesRoute: AuthenticatedStrategiesRoute,
  AuthenticatedTradeRoute: AuthenticatedTradeRoute,
  AuthenticatedValidationRoute: AuthenticatedValidationRoute,
  AuthenticatedRunsRunIdRoute: AuthenticatedRunsRunIdRoute,
  AuthenticatedValidationStudyIdRoute: AuthenticatedValidationStudyIdRoute,
  AuthenticatedValidationCampaignsCampaignIdRoute:
    AuthenticatedValidationCampaignsCampaignIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInCallbackRoute: SignInCallbackRoute,
  SignInIndexRoute: SignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
