/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as SignInMfaRouteImport } from './routes/sign-in/mfa'
import { Route as SignInCallbackRouteImport } from './routes/sign-in/callback'
import { Route as AuthenticatedStrategiesRouteImport } from './routes/_authenticated.strategies'
import { Route as AuthenticatedRunsRouteImport } from './routes/_authenticated.runs'
import { Route as AuthenticatedMfaEnrollRouteImport } from './routes/_authenticated.mfa-enroll'
import { Route as AuthenticatedRunsRunIdRouteImport } from './routes/_authenticated.runs_.$runId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInMfaRoute = SignInMfaRouteImport.update({
  id: '/sign-in/mfa',
  path: '/sign-in/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInCallbackRoute = SignInCallbackRouteImport.update({
  id: '/sign-in/callback',
  path: '/sign-in/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStrategiesRoute = AuthenticatedStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRunsRoute = AuthenticatedRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMfaEnrollRoute = AuthenticatedMfaEnrollRouteImport.update({
  id: '/mfa-enroll',
  path: '/mfa-enroll',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRunsRunIdRoute = AuthenticatedRunsRunIdRouteImport.update({
  id: '/runs_/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mfa-enroll': typeof AuthenticatedMfaEnrollRoute
  '/runs': typeof AuthenticatedRunsRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/sign-in/callback': typeof SignInCallbackRoute
  '/sign-in/mfa': typeof SignInMfaRoute
  '/sign-in/': typeof SignInIndexRoute
  '/runs/$runId': typeof AuthenticatedRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mfa-enroll': typeof AuthenticatedMfaEnrollRoute
  '/runs': typeof AuthenticatedRunsRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/sign-in/callback': typeof SignInCallbackRoute
  '/sign-in/mfa': typeof SignInMfaRoute
  '/sign-in': typeof SignInIndexRoute
  '/runs/$runId': typeof AuthenticatedRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/mfa-enroll': typeof AuthenticatedMfaEnrollRoute
  '/_authenticated/runs': typeof AuthenticatedRunsRoute
  '/_authenticated/strategies': typeof AuthenticatedStrategiesRoute
  '/sign-in/callback': typeof SignInCallbackRoute
  '/sign-in/mfa': typeof SignInMfaRoute
  '/sign-in/': typeof SignInIndexRoute
  '/_authenticated/runs_/$runId': typeof AuthenticatedRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mfa-enroll'
    | '/runs'
    | '/strategies'
    | '/sign-in/callback'
    | '/sign-in/mfa'
    | '/sign-in/'
    | '/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mfa-enroll'
    | '/runs'
    | '/strategies'
    | '/sign-in/callback'
    | '/sign-in/mfa'
    | '/sign-in'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/mfa-enroll'
    | '/_authenticated/runs'
    | '/_authenticated/strategies'
    | '/sign-in/callback'
    | '/sign-in/mfa'
    | '/sign-in/'
    | '/_authenticated/runs_/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInCallbackRoute: typeof SignInCallbackRoute
  SignInMfaRoute: typeof SignInMfaRoute
  SignInIndexRoute: typeof SignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/mfa': {
      id: '/sign-in/mfa'
      path: '/sign-in/mfa'
      fullPath: '/sign-in/mfa'
      preLoaderRoute: typeof SignInMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/callback': {
      id: '/sign-in/callback'
      path: '/sign-in/callback'
      fullPath: '/sign-in/callback'
      preLoaderRoute: typeof SignInCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/strategies': {
      id: '/_authenticated/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof AuthenticatedStrategiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/runs': {
      id: '/_authenticated/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AuthenticatedRunsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mfa-enroll': {
      id: '/_authenticated/mfa-enroll'
      path: '/mfa-enroll'
      fullPath: '/mfa-enroll'
      preLoaderRoute: typeof AuthenticatedMfaEnrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/runs_/$runId': {
      id: '/_authenticated/runs_/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AuthenticatedRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedMfaEnrollRoute: typeof AuthenticatedMfaEnrollRoute
  AuthenticatedRunsRoute: typeof AuthenticatedRunsRoute
  AuthenticatedStrategiesRoute: typeof AuthenticatedStrategiesRoute
  AuthenticatedRunsRunIdRoute: typeof AuthenticatedRunsRunIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMfaEnrollRoute: AuthenticatedMfaEnrollRoute,
  AuthenticatedRunsRoute: AuthenticatedRunsRoute,
  AuthenticatedStrategiesRoute: AuthenticatedStrategiesRoute,
  AuthenticatedRunsRunIdRoute: AuthenticatedRunsRunIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInCallbackRoute: SignInCallbackRoute,
  SignInMfaRoute: SignInMfaRoute,
  SignInIndexRoute: SignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
